"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Head = exports.Patch = exports.Delete = exports.Put = exports.Post = exports.Get = exports.Request = exports.Client = void 0;
var Client_1 = require("./Client");
Object.defineProperty(exports, "Client", { enumerable: true, get: function () { return Client_1.Client; } });
var Request_1 = require("./Request");
Object.defineProperty(exports, "Request", { enumerable: true, get: function () { return Request_1.Request; } });
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return Request_1.Get; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return Request_1.Post; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return Request_1.Put; } });
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return Request_1.Delete; } });
Object.defineProperty(exports, "Patch", { enumerable: true, get: function () { return Request_1.Patch; } });
Object.defineProperty(exports, "Head", { enumerable: true, get: function () { return Request_1.Head; } });
